news_sites:
  hipertextual:
    url: https://hipertextual.com
    queries:
      homepage_article_links: '.entry-title a'
      article_body: '.entry-content'
      article_title: '.entry-header h1'
  xakata:
    url: https://www.xataka.com.mx/
    queries:
      homepage_article_links: '.abstract-title a'
      article_body: '.article-content'
      article_title: '.article-header span'
  genbeta:
    url: https://www.genbeta.com
    queries:
      homepage_article_links: '.abstract-title a'
      article_body: '.article-content'
      article_title: '.article-header span'